#!/bin/sh
# After installing vulcan-headers

# Play a 10bit HEVC video with:
# ~/git/mpv-build/mpv/build/mpv --hwdec=cuda --vo=opengl <VIDEO_FILE>

mkdir -p ~/git
cd ~/git
git clone https://github.com/mpv-player/mpv-build.git
cd mpv-build

# write mpv_options file
cat << EOF > mpv_options
--enable-cuda-hwaccel
EOF

# write ffmpeg_options file
cat << EOF > ffmpeg_options
--enable-cuda
--enable-cuvid
--enable-nonfree
EOF

# build
./rebuild -j10
