#!/bin/bash

# A simple alarm clock script

echo "how long until alarm (HH:MM)"
read target

# convert wakeup time to seconds
target_h=`echo $target | awk -F: '{print $1}'`
target_m=`echo $target | awk -F: '{print $2}'`
let "target_s_t=$target_h * 60 * 60 + $target_m * 60"
echo $target_s_t

sleep $target_s_t
mpv "mymovie.mkv"
