#!/bin/bash
# 
# Returns the PID of the application in window with focus

# Get window ID
ID=$(xdpyinfo | grep focus | cut -f4 -d " ")

# Get PID of process whose window this is
PID=$(xprop -id $ID | grep -m 1 PID | cut -d " " -f 3)
echo "$PID"

# Get last child process (shell, vim, etc)
#if [ -n "$PID" ]; then
#  TREE=$(pstree -lpA $PID | tail -n 1)
#  PID=$(echo $TREE | awk -F'---' '{print $NF}' | sed -re 's/[^0-9]//g')
#fi

