#!/usr/bin/sh
# Summary: i3-lock script that just shows a simple image
# Depends: i3lock
# Adjusted to just use the background image since pixelating takes time

#icon="$HOME/Pictures/lock.png"
#current_wallpaper="$(< ~/.cache/wal/wal)"
lock_image="$HOME/Pictures/lock_image.png"

#convert "$current_wallpaper" "$icon" -gravity center -composite -matte "$lock_image"
/usr/bin/i3lock -u -t -i "$lock_image"

#i3lockpid=$!
#sleep 0.5

#winid=`xwininfo -name "i3lock" | grep "Window id" | grep -oE "0x[0-9a-f]+"`
#if [ -z "$winid" ]
#then
    #echo "Could not find i3lock window"
    #exit 1
#fi

#conky -w "$winid" &
#conkypid=$!

#wait $i3lockpid
#kill $conkypid


