#!/usr/bin/env bash
# Adjusted to just use the background image since pixelating takes time
icon="$HOME/Pictures/lock.png"
current_wallpaper="$(< ~/.cache/wal/wal)"
lock_image="$HOME/Pictures/lock_image.png"

convert "$current_wallpaper" "$icon" -gravity center -composite -matte "$lock_image"
i3lock -u -t -i "$lock_image"
