#!/usr/bin/env bash

icon="$HOME/Pictures/lock.png"
tmpbg='/tmp/screen.png'

scr
convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
convert "$tmpbg" "$icon" -gravity West -composite -matte "$tmpbg"
i3lock -u -i "$tmpbg"
