#!/bin/sh

res=$(echo -e "lock\nexit\nrestart\nshutdown" | rofi -dmenu)

if [ $res = "lock" ]; then
  ~/bin/lock
fi
if [ $res = "exit" ]; then
  i3-msg exit
fi
if [ $res = "restart" ]; then
    reboot
fi
if [ $res = "shutdown" ]; then
    poweroff
fi
exit 0
