#!/usr/bin/sh
#
# Summary: Take a screenshot and display a notification.
#
# Summary: Created by Dylan Araps.
#
# Depends: imagemagick, libnotify (patched with id support)

# Screenshot directory
scr_dir="${HOME}/Pictures/Screenshots"
mkdir -p "$scr_dir" || { printf "%s\\n" "Error: Couldn't create screenshot directory"; exit; }

# Use printf to store the current date/time as variables.
date=$(printf "%(%F)T")
time=$(printf "%(%I-%M-%S)T")

# Create current date format.
mkdir -p "${scr_dir}/${date}"

# Name the screenshot
scr="${scr_dir}/${date}/${date}-${time}.png"

# The '-r' flag is from a patched version of 'libnotify'.
# '-r' lets you replace notifications using the same id.
notify-send "Saved screenshot as $( basename "$scr" )"

import -window root -gravity north "$scr"
