#!/usr/bin/env bash
#
# Send a text message to my phone
#
# Created by Ryan Bell
#
# Depends on: ssmtp (or mutt, nail, postfix, etc)
# If using gmail, Allow Less Secure Apps needs to be enabled
# /etc/ssmtp.conf -- the config file for sSMTP sendmail needs to be editted like:
#
#		root=youraccount@gmail.com
#		mailhub=smtp.gmail.com:587
#		rewriteDomain=
#		hostname=youraccount.gmail.com
#		UseSTARTTLS=YES
#		AuthUser=youraccount
#		AuthPass=youraccountpass
#		FromLineOverride=YES
#
# /etc/ssmtp/revaliases -- needs to be editted like:
#
#		root:youraccount@gmail.com:smtp.gmail.com:587
#		mainuser:youraccount@gmail.com:smtp.gmail.com:587
#
# You can test proper ssmtp set up with:
#		echo "hello mail" | mail -s "test subject" USERNAME@SOMEDOMAIN.COM

echo "$1" | mail -s "Archer Update" 2678930688@txt.att.net
