#!/bin/sh
# Generates the repo readme based on descriptions in the scripts

#TODO(ryan) can this be done with grep and exclude=?
#TODO(ryan) summary is matched on this file at grep line
#TODO(ryan) multiple summary lines aren't being split in markdown

exclude_list=("hub" "README" "update_readme")

containsElement () {
	local e match="$1"
	shift
	for e; do [[ "$e" == "$match" ]] && return 0; done
	return 1
}

# README description
echo "A collection of scripts I use  " > README.md

for script in ~/bin/*; do
	[ -e "$script" ] || continue
	script_extension=".${script##*.}"
	script_filename=$(basename "$script" "$script_extension")
	if containsElement "$script_filename" "${exclude_list[@]}"; then
		echo "SKIP $script_filename"
	else
		# Not in exclude list extract header information and append to readme
		# Only continue if there is a summary
		grep -q "Summary:" "$script" || continue

		# Print script filename as header
		echo "### $script_filename  " >> README.md
		# Print summary and append spaces at end for line break
		echo "$(grep "Summary:" "$script" | sed "s/^.*:\\ //")  " >> README.md
	fi
done
printf "%`tput cols`s"|tr ' ' '-'
cat README.md
