#!/bin/sh
# Summary: Shows what HTTP codes mean
# Summary: from coldsauce/whatishttp adapted to shell

usage(){
	printf "usage: whatishttp HTTP_CODE\\n"
}

if [ $# -eq 0 ]; then
	usage
	exit 1
fi

case $1 in
	100 )
		printf "Continue"
		printf "\\n\\n"
		printf "This interim response indicates that everything so far is OK and that the client should continue with the request or ignore it if it is already finished."
		printf "\\n"
		exit;;
	101 )
		printf "Switching Protocol"
		printf "\\n\\n"
		printf "This code is sent in response to an Upgrade request header by the client, and indicates the protocol the server is switching too."
		printf "\\n"
		exit;;
	103 )
		printf "Processing (WebDAV)"
		printf "\\n\\n"
		printf "This code indicates that the server has received and is processing the request, but no response is available yet."
		printf "\\n"
		exit;;
	200 )
		printf "OK"
		printf "\\n\\n"
		printf "The request has succeeded. The meaning of a success varies depending on the HTTP method:\\nGET: The resource has been fetched and is transmitted in the message body.\\nHEAD: The entity headers are in the message body.\\nPOST: The resource describing the result of the action is transmitted in the message body.\\nTRACE: The message body contains the request message as received by the server"
		printf "\\n"
		exit;;
	201 )
		printf "Created"
		printf "\\n\\n"
		printf "The request has succeeded and a new resource has been created as a result of it. This is typically the response sent after a PUT request."
		printf "\\n"
		exit;;
	202 )
		printf "Accepted"
		printf "\\n\\n"
		printf "The request has been received but not yet acted upon. It is non-committal, meaning that there is no way in HTTP to later send an asynchronous response indicating the outcome of processing the request. It is intended for cases where another process or server handles the request, or for batch processing."
		printf "\\n"
		exit;;
	203 )
		printf "Non-Authoritative Information"
		printf "\\n\\n"
		printf "This response code means returned meta-information set is not exact set as available from the origin server, but collected from a local or a third party copy. Except this condition, 200 OK response should be preferred instead of this response."
		printf "\\n"
		exit;;
	204 )
		printf "No Content"
		printf "\\n\\n"
		printf "There is no content to send for this request, but the headers may be useful. The user-agent may update its cached headers for this resource with the new ones."
		printf "\\n"
		exit;;
	205 )
		printf "Reset Content"
		printf "\\n\\n"
		printf "This response code is sent after accomplishing request to tell user agent reset document view which sent this request."
		printf "\\n"
		exit;;
	206 )
		printf "Partial Content"
		printf "\\n\\n"
		printf "This response code is used because of range header sent by the client to separate download into multiple streams."
		printf "\\n"
		exit;;
	207 )
		printf "Multi-Status (WebDAV)"
		printf "\\n\\n"
		printf "A Multi-Status response conveys information about multiple resources in situations where multiple status codes might be appropriate."
		printf "\\n"
		exit;;
	208 )
		printf "Multi-Status (WebDAV)"
		printf "\\n\\n"
		printf "Used inside a DAV: propstat response element to avoid enumerating the internal members of multiple bindings to the same collection repeatedly."
		printf "\\n"
		exit;;
	226 )
		printf "IM Used (HTTP Delta encoding)"
		printf "\\n\\n"
		printf "The server has fulfilled a GET request for the resource, and the response is a representation of the result of one or more instance-manipulations applied to the current instance."
		printf "\\n"
		exit;;
	300 )
		printf "Multiple Choice"
		printf "\\n\\n"
		printf "The request has more than one possible responses. User-agent or user should choose one of them. There is no standardized way to choose one of the responses."
		printf "\\n"
		exit;;
	301 )
		printf "Moved Permanently"
		printf "\\n\\n"
		printf "This response code means that URI of requested resource has been changed. Probably, new URI would be given in the response."
		printf "\\n"
		exit;;
	302 )
		printf "Found"
		printf "\\n\\n"
		printf "This response code means that URI of requested resource has been changed temporarily. New changes in the URI might be made in the future. Therefore, this same URI should be used by the client in future requests."
		printf "\\n"
		exit;;
	303 )
		printf "See Other"
		printf "\\n\\n"
		printf "Server sent this response to directing client to get requested resource to another URI with an GET request."
		printf "\\n"
		exit;;
	304 )
		printf "Not Modified"
		printf "\\n\\n"
		printf "This is used for caching purposes. It is telling to client that response has not been modified. So, client can continue to use same cached version of response."
		printf "\\n"
		exit;;
	305 )
		printf "Use Proxy "
		printf "\\n\\n"
		printf "Was defined in a previous version of the HTTP specification to indicate that a requested response must be accessed by a proxy. It has been deprecated due to security concerns regarding in-band configuration of a proxy."
		printf "\\n"
		exit;;
	306 )
		printf "unused"
		printf "\\n\\n"
		printf "This response code is no longer used, it is just reserved currently. It was used in a previous version of the HTTP 1.1 specification."
		printf "\\n"
		exit;;
	307 )
		printf "Temporary Redirect"
		printf "\\n\\n"
		printf "Server sent this response to directing client to get requested resource to another URI with same method that used prior request. This has the same semantic than the 302 Found HTTP response code, with the exception that the user agent must not change the HTTP method used: if a POST was used in the first request, a POST must be used in the second request."
		printf "\\n"
		exit;;
	308 )
		printf "Permanent Redirect"
		printf "\\n\\n"
		printf "This means that the resource is now permanently located at another URI, specified by the Location: HTTP Response header. This has the same semantics as the 301 Moved Permanently HTTP response code, with the exception that the user agent must not change the HTTP method used: if a POST was used in the first request, a POST must be used in the second request."
		printf "\\n"
		exit;;
	400 )
		printf "Bad Request"
		printf "\\n\\n"
		printf "This response means that server could not understand the request due to invalid syntax."
		printf "\\n"
		exit;;
	401 )
		printf "Unauthorized"
		printf "\\n\\n"
		printf "Authentication is needed to get requested response. This is similar to 403, but in this case, authentication is possible."
		printf "\\n"
		exit;;
	402 )
		printf "Payment Required"
		printf "\\n\\n"
		printf "This response code is reserved for future use. Initial aim for creating this code was using it for digital payment systems however this is not used currently."
		printf "\\n"
		exit;;
	403 )
		printf "Forbidden"
		printf "\\n\\n"
		printf "Client does not have access rights to the content so server is rejecting to give proper response."
		printf "\\n"
		exit;;
	404 )
		printf "Not Found"
		printf "\\n\\n"
		printf "Server can not find requested resource. This response code probably is most famous one due to its frequency to occur in web."
		printf "\\n"
		exit;;
	405 )
		printf "Method Not Allowed"
		printf "\\n\\n"
		printf "The request method is known by the server but has been disabled and cannot be used. The two mandatory methods, GET and HEAD, must never be disabled and should not return this error code."
		printf "\\n"
		exit;;
	406 )
		printf "Not Acceptable"
		printf "\\n\\n"
		printf "This response is sent when the web server, after performing server-driven content negotiation, doesn't find any content following the criteria given by the user agent."
		printf "\\n"
		exit;;
	407 )
		printf "Proxy Authentication Required"
		printf "\\n\\n"
		printf "This is similar to 401 but authentication is needed to be done by a proxy."
		printf "\\n"
		exit;;
	408 )
		printf "Request Timeout"
		printf "\\n\\n"
		printf "This response is sent on an idle connection by some servers, even without any previous request by the client. It means that the server would like to shut down this unused connection. This response is used much more since some browsers, like Chrome, Firefox 27+, or IE9, use HTTP pre-connection mechanisms to speed up surfing. Also note that some servers merely shut down the connection without sending this message."
		printf "\\n"
		exit;;
	409 )
		printf "Conflict"
		printf "\\n\\n"
		printf "This response would be sent when a request conflict with current state of server."
		printf "\\n"
		exit;;
	410 )
		printf "Gone"
		printf "\\n\\n"
		printf "This response would be sent when requested content has been deleted from server."
		printf "\\n"
		exit;;
	411 )
		printf "Length Required"
		printf "\\n\\n"
		printf "Server rejected the request because the Content-Length header field is not defined and the server requires it."
		printf "\\n"
		exit;;
	412 )
		printf "Precondition Failed"
		printf "\\n\\n"
		printf "The client has indicated preconditions in its headers which the server does not meet."
		printf "\\n"
		exit;;
	413 )
		printf "Payload Too Large"
		printf "\\n\\n"
		printf "Request entity is larger than limits defined by server; the server might close the connection or return an Retry-After header field."
		printf "\\n"
		exit;;
	414 )
		printf "URI Too Long"
		printf "\\n\\n"
		printf "The URI requested by the client is longer than the server is willing to interpret."
		printf "\\n"
		exit;;
	415 )
		printf "Unsupported Media Type"
		printf "\\n\\n"
		printf "The media format of the requested data is not supported by the server, so the server is rejecting the request."
		printf "\\n"
		exit;;
	416 )
		printf "Requested Range Not Satisfiable"
		printf "\\n\\n"
		printf "The range specified by the Range header field in the request can't be fulfilled; it's possible that the range is outside the size of the target URI's data."
		printf "\\n"
		exit;;
	417 )
		printf "Expectation Failed"
		printf "\\n\\n"
		printf "This response code means the expectation indicated by the Expect request header field can't be met by the server."
		printf "\\n"
		exit;;
	418 )
		printf "I'm a teapot"
		printf "\\n\\n"
		printf "The server refuses the attempt to brew coffee with a teapot."
		printf "\\n"
		exit;;
	421 )
		printf "Misdirected Request"
		printf "\\n\\n"
		printf "The request was directed at a server that is not able to produce a response. This can be sent by a server that is not configured to produce responses for the combination of scheme and authority that are included in the request URI."
		printf "\\n"
		exit;;
	422 )
		printf "Unprocessable Entity (WebDAV)"
		printf "\\n\\n"
		printf "The request was well-formed but was unable to be followed due to semantic errors."
		printf "\\n"
		exit;;
	423 )
		printf "Locked (WebDAV)"
		printf "\\n\\n"
		printf "The resource that is being accessed is locked."
		printf "\\n"
		exit;;
	424 )
		printf "Failed Dependency (WebDAV)"
		printf "\\n\\n"
		printf "The request failed due to failure of a previous request."
		printf "\\n"
		exit;;
	426 )
		printf "Upgrade Required"
		printf "\\n\\n"
		printf "The server refuses to perform the request using the current protocol but might be willing to do so after the client upgrades to a different protocol. The server sends an Upgrade header in a 426 response to indicate the required protocol(s)."
		printf "\\n"
		exit;;
	428 )
		printf "Precondition Required"
		printf "\\n\\n"
		printf "The origin server requires the request to be conditional. Intended to prevent the 'lost update' problem, where a client GETs a resource's state, modifies it, and PUTs it back to the server, when meanwhile a third party has modified the state on the server, leading to a conflict."
		printf "\\n"
		exit;;
	429 )
		printf "Too Many Requests"
		printf "\\n\\n"
		printf "The user has sent too many requests in a given amount of time (\"rate limiting\")."
		printf "\\n"
		exit;;
	431 )
		printf "Request Header Fields Too Large"
		printf "\\n\\n"
		printf "The server is unwilling to process the request because its header fields are too large. The request MAY be resubmitted after reducing the size of the request header fields."
		printf "\\n"
		exit;;
	451 )
		printf "Unavailable For Legal Reasons"
		printf "\\n\\n"
		printf "The user requests an illegal resource, such as a web page censored by a government."
		printf "\\n"
		exit;;
	500 )
		printf "Internal Server Error"
		printf "\\n\\n"
		printf "The server has encountered a situation it doesn't know how to handle."
		printf "\\n"
		exit;;
	501 )
		printf "Not Implemented"
		printf "\\n\\n"
		printf "The request method is not supported by the server and cannot be handled. The only methods that servers are required to support (and therefore that must not return this code) are GET and HEAD."
		printf "\\n"
		exit;;
	502 )
		printf "Bad Gateway"
		printf "\\n\\n"
		printf "This error response means that the server, while working as a gateway to get a response needed to handle the request, got an invalid response."
		printf "\\n"
		exit;;
	503 )
		printf "Service Unavailable"
		printf "\\n\\n"
		printf "The server is not ready to handle the request. Common causes are a server that is down for maintenance or that is overloaded. Note that together with this response, a user-friendly page explaining the problem should be sent. This responses should be used for temporary conditions and the Retry-After: HTTP header should, if possible, contain the estimated time before the recovery of the service. The webmaster must also take care about the caching-related headers that are sent along with this response, as these temporary condition responses should usually not be cached."
		printf "\\n"
		exit;;
	504 )
		printf "Gateway Timeout"
		printf "\\n\\n"
		printf "This error response is given when the server is acting as a gateway and cannot get a response in time."
		printf "\\n"
		exit;;
	505 )
		printf "HTTP Version Not Supported"
		printf "\\n\\n"
		printf "The HTTP version used in the request is not supported by the server."
		printf "\\n"
		exit;;
	506 )
		printf "Variant Also Negotiates"
		printf "\\n\\n"
		printf "The server has an internal configuration error: transparent content negotiation for the request results in a circular reference."
		printf "\\n"
		exit;;
	507 )
		printf "Insufficient Storage"
		printf "\\n\\n"
		printf "The server has an internal configuration error: the chosen variant resource is configured to engage in transparent content negotiation itself, and is therefore not a proper end point in the negotiation process."
		printf "\\n"
		exit;;
	508 )
		printf "Loop Detected (WebDAV)"
		printf "\\n\\n"
		printf "The server detected an infinite loop while processing the request."
		printf "\\n"
		exit;;
	510 )
		printf "Not Extended"
		printf "\\n\\n"
		printf "Further extensions to the request are required for the server to fulfill it."
		printf "\\n"
		exit;;
	511 )
		printf "Network Authentication Required"
		printf "\\n\\n"
		printf "The 511 status code indicates that the client needs to authenticate to gain network access."
		printf "\\n"
		exit;;
esac
